#! /bin/sh

killall -q sxhkd
while pgrep -u $UID -x sxhkd >/dev/null; do sleep 1; done
sxhkd &
dunst &

bspc monitor eDP1 -d terminal code web video free  

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^5' state=floating follow=on
bspc rule -a Chromium desktop='^3' follow=on
bspc rule -a Firefox desktop='^3' follow=on
bspc rule -a st desktop='^1','^2'
