#! /bin/sh

# Load background image
~/.fehbg

# Start Polybar
~/.config/polybar/launch.sh

# Start light-locker
light-locker &

# Hotkeys
killall -q sxhkd
while pgrep -u $UID -x sxhkd >/dev/null; do sleep 1; done
sxhkd &

# Start notification daemon
killall -q dunst
while pgrep -u $UID -x dunst >/dev/null; do sleep 1; done
dunst &

bspc monitor eDP1 -d 1 2 3 4 5
bspc monitor HDMI1 -d 6 7 8 9 0

bspc config border_width		1
bspc config window_gap			7
bspc config focus_follows_pointer	true

bspc config focused_border_color	\#0B76DE
bspc config normal_border_color		\#252525

bspc config split_ratio			0.50
bspc config borderless_monocle		true
bspc config gapless_monocle		true

bspc rule -a Gimp desktop='^5' state=floating follow=on
bspc rule -a barToggle.sh layer=above

bspc rule -a scratchpad sticky=on state=floating layer=above hidden=on 
