#! /bin/sh

# Hotkeys
killall -q sxhkd
while pgrep -u $UID -x sxhkd >/dev/null; do sleep 1; done
sxhkd &


# Start notification daemon
killall -q dunst
while pgrep -u $UID -x dunst >/dev/null; do sleep 1; done
dunst &

# Load background image
~/.fehbg

bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9

bspc config border_width		2
bspc config window_gap			10
bspc config focus_follows_pointer	true

bspc config focused_border_color	\#0B76DE
bspc config normal_border_color		\#252525

bspc config split_ratio			0.50
bspc config borderless_monocle		true
bspc config gapless_monocle		true

bspc rule -a Gimp desktop='^5' state=floating follow=on
bspc rule -a Firefox desktop='^2' follow=on
